### PR TITLE
Added On duplicate key update functionality

### PR DESCRIPTION
**Pull request by lekoaf**
I added functionality to use [ON DUPLICATE KEY UPDATE](http://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html). You will have to check if it works for all use cases because I only made it work for mine.

### CODE REVIEW

**Comment by LaNsHoR** [comment]
Thank you so much. I'll check it soon! 

In your example:

``` php
$bdb->insert_into("fruits")->values(null, "tomato", 4.2, $my_variable)->on_duplicate_key_update(['price', 4.2])->exec();
```

Must be (equal character after price):

``` php
$bdb->insert_into("fruits")->values(null, "tomato", 4.2, $my_variable)->on_duplicate_key_update(['price =', 4.2])->exec();
```

The equal is important to maintain the equivalence with MySQL syntax.

I'll check with all cases in the next days :)

**Comment by lekoaf** [comment]
Just let me know what to change and I'll be happy to update it.

**Comment by lekoaf** [comment]
Fixed it according to your comments and refactored it a bit to keep it DRY.

**Comment by LaNsHoR** [comment]
Done!

I've tested it and I made some changes, I've extracted the code for "set" and now this code is shared with "on_duplicate_key_update" method.

On this way, both accept the same options with the same format.

Thank you for your help!

**Comment by lekoaf** [comment]
Excellent. That's much better, using an already existing function to do the heavy lifting. :)

**Pull request merged**
